<?php
/**
 * PROJECT: NAVA AI - Database Setup Engine
 * ENGINEER: NAWAF_ROOT (Generated by Gemini Code Assist)
 * PURPOSE: To create the necessary tables for the application to run.
 */

// Set error reporting for debugging
ini_set('display_errors', 1);
error_reporting(E_ALL);

// HTML and CSS for better display
echo <<<HTML
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>إعداد قاعدة بيانات NAVA</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        body { background-color: #0d1117; color: #c9d1d9; font-family: monospace, sans-serif; padding: 20px; line-height: 1.6; }
        .container { max-width: 800px; margin: 40px auto; border: 1px solid #30363d; border-radius: 8px; padding: 25px; box-shadow: 0 0 20px rgba(0,0,0,0.5); }
        h1 { color: #00f3ff; text-align: center; }
        .log { border: 1px solid #30363d; border-radius: 5px; padding: 15px; margin-bottom: 10px; }
        .success { color: #3fb63f; border-left: 3px solid #3fb63f; }
        .error { color: #ff6c6b; border-left: 3px solid #ff6c6b; }
        .info { color: #79c0ff; }
        .warning { color: #d29922; font-weight: bold; background-color: rgba(210, 153, 34, 0.1); padding: 15px; border-radius: 5px; text-align: center; }
    </style>
</head>
<body>
    <div class="container">
        <h1><i class="fa-solid fa-database"></i> إعداد قاعدة بيانات NAVA</h1>
HTML;

try {
    // 1. Include the database connection file
    require_once 'config/database.php';
    echo "<div class='log success'>✓ تم الاتصال بقاعدة البيانات بنجاح.</div>";

    // 2. SQL statements to create tables
    $sql_statements = [
        "users" => "CREATE TABLE IF NOT EXISTS `users` (
                      `id` INT AUTO_INCREMENT PRIMARY KEY,
                      `name` VARCHAR(255) NOT NULL UNIQUE,
                      `password` VARCHAR(255) NOT NULL,
                      `bio` TEXT,
                      `profile_pic` VARCHAR(255) DEFAULT 'default-avatar.png',
                      `access_level` VARCHAR(50) DEFAULT 'USER',
                      `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;",

        "chats" => "CREATE TABLE IF NOT EXISTS `chats` (
                      `id` INT AUTO_INCREMENT PRIMARY KEY,
                      `user_id` INT NOT NULL,
                      `title` VARCHAR(255) NOT NULL,
                      `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;",

        "messages" => "CREATE TABLE IF NOT EXISTS `messages` (
                         `id` INT AUTO_INCREMENT PRIMARY KEY,
                         `chat_id` INT NOT NULL,
                         `sender_type` VARCHAR(50) NOT NULL,
                         `content` TEXT NOT NULL,
                         `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         FOREIGN KEY (`chat_id`) REFERENCES `chats`(`id`) ON DELETE CASCADE
                       ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;"
    ];

    // 3. Execute each statement
    foreach ($sql_statements as $table => $sql) {
        $pdo->exec($sql);
        echo "<div class='log success'>✓ تم إنشاء جدول '{$table}' بنجاح (أو كان موجوداً بالفعل).</div>";
    }

    echo "<h2 class='success' style='text-align:center;'>🎉 اكتمل الإعداد!</h2>";
    echo "<p class='info' style='text-align:center;'>تم إنشاء جميع الجداول المطلوبة في قاعدة البيانات الخاصة بك.</p>";
    echo "<p class='warning'><i class='fa-solid fa-triangle-exclamation'></i> لأسباب أمنية، يرجى حذف هذا الملف (setup_database.php) من الخادم الآن.</p>";

} catch (Exception $e) {
    echo "<div class='log error'>✗ فشل حرج: " . htmlspecialchars($e->getMessage()) . "</div>";
    echo "<p class='error'>لم يتمكن النظام من الاتصال بقاعدة البيانات. يرجى التحقق من المعلومات في ملف 'config/database.php' والتأكد من أن خدمة قاعدة البيانات تعمل.</p>";
}

echo "</div></body></html>";

?>